kind: project
metadata:
  name: aa-gilad
  created: '2022-09-29T11:48:45.523000'
spec:
  functions:
  - url: db://gilad-testing/add-2
    name: add-2
  workflows:
  - path: workflow.py
    name: testing
    schedule: '*/10 * * * *'
  artifacts: []
  source: ''
  desired_state: online
  owner: shapira
status:
  state: online
