kind: project
metadata:
  name: taxi-cli
spec:
  params:
    label_column: label
  functions:
  - url: taxi.py
    name: taxi
    image: mlrun/mlrun
    requirements: ['lightgbm','shapely']
  workflows:
  - name: main
    path: ./workflow.py
    handler: kfpipeline
    engine: kfp
  artifacts:
  - kind: ''
    target_path: https://s3.wasabisys.com/iguazio/data/iris/iris.data.raw.csv
    key: data
  source: ./
  subpath: ''
  origin_url: ''
  load_source_on_run: true
  desired_state: online
